#!/bin/bash

set -e -o pipefail
shopt -s inherit_errexit

# URL
URL=https://www.the-paper-trail.org

# download page
SRC="$(mktemp)"

trap "rm -f $SRC" EXIT SIGTERM SIGINT SIGQUIT SIGHUP

hxnormalize -s -x -l 1000000 "$URL" 	\
| hxselect .post-preview	\
| hxremove .the-big-idea, .alert	\
| hxremove script, .twitter-tweet	\
| sed 's/&nbsp;|\?//g'	\
> "$SRC"

# debug
#SRC=src.html

# current timestamp
NOW="$(date --rfc-email)"

# header
cat <<EOF
<?xml version="1.0"?>
<rss version="2.0">
<channel>
<title>The Paper Trail</title>
<link>$URL</link>
<description>Distributed systems and data processing</description>
<language>en-us</language>
<pubDate>$NOW</pubDate>
<lastBuildDate>$NOW</lastBuildDate>
<generator>$(basename "$0")</generator>

EOF

# helper functions
take() {
	set -o pipefail # ???
	hxselect -c -s '\n' "$@" < "$SRC"
}

fix_text() {
	hxunent -bf | sed -E -e 's/[[:space:]]+/ /g'
}

extract_dates() {
	hxremove .fa	\
	| grep -oE '[A-Z][a-z]+ [[:digit:]]{1,2}, 20[[:digit:]]{2}'	\
	| TZ="America/New_York" xargs -n 1 -L 1 -I % date --rfc-email -d "12:00 %"
}

# process source file
paste -d '\n'	\
	<(take .post-title | fix_text)	\
	<(take .post-read-more::attr\(href\))	\
	<(take .post-preview \> .post-meta | extract_dates)	\
| nl -n ln -v 0	\
| while IFS=$'\t' read -r no line
do
	case $((no % 3)) in
		0)	echo '<item>'
			echo "<title>$line</title>"
			;;
		1)	echo "<link>$line</link>"
			echo "<guid>$line</guid>"
			;;
		2)	echo "<pubDate>$line</pubDate>"
			echo -e "</item>\n"
			;;
	esac
done

# close tags
echo "</channel></rss>"
