#!/usr/bin/env bash

set -e -o pipefail
shopt -s inherit_errexit

# URL
readonly URL_BASE=https://rutracker.org/forum
readonly URL=${1:-$URL_BASE/viewforum.php?f=1950}

# temporary file
readonly SRC="$(mktemp)"

trap "rm -f $SRC" EXIT SIGTERM SIGINT SIGQUIT SIGHUP

# download and pre-process the page
hxnormalize -s -x -e -l 1000000 "$URL"	\
| iconv -f WINDOWS-1251 -t UTF8	\
| sed -E 's/(<\/?style>)/\n\1\n/g'	\
| sed '/^<style>$/,/^<\/style>$/d'	\
| hxselect -s '\n' tr.hl-tr	\
| hxremove 'td[class^="vf-col-icon"], td[class^="vf-col-last-post"]'	\
> "$SRC"

# selector funtions
take() {
	hxselect -c "$@" < "$SRC"
}

grab() {
	# multiline records, each converted to a single line
	take -s $'\x1f' "$@" \
	| tr -d '\n'	\
	| tr $'\x1f' '\n'
}

# topic IDs
topics() {
	take -s '\n' .hl-tr::attr\(data-topic_id\)
}

# topic titles
titles() {
	take -s $'\x1F' 'td > div.torTopic > a'	\
	| awk -v RS=$'\x1F' '{
		gsub(/\><wbr><\/wbr>\s+\</, "")
		gsub(/<wbr><\/wbr>/, "")
		gsub(/\s+/, " ")
		print
	}'	\
	| hxunent -bf
}

# number of downloads
downloads() {
	grab 'td[class^="vf-col-replies"]'	\
	| awk '
		match($0, /<b>([0-9,]+)<\/b>/, a)	{ gsub(/,+/, "", a[1]); print a[1]; next }
											{ print "[unknown]" }'
}

# file sizes
sizes() {
	grab 'td[class^="vf-col-tor"]'	\
	| awk '
		/^\s*$/									{ print "[unknown]"; next }
		match($0, />([^<]+)<\/a><\/div>/, a)	{ print a[1]; next }
												{ print "[???]" }'	\
	| hxunent -bf
}

# current timestamp
readonly NOW="$(date --rfc-email)"

# RSS header
cat <<EOF
<?xml version="1.0"?>
<rss version="2.0">
<channel>
<title>Фильмы 2019</title>
<description>Фильмы 2019</description>
<link>$URL</link>
<language>ru</language>
<pubDate>$NOW</pubDate>
<lastBuildDate>$NOW</lastBuildDate>
<generator>$(basename "$0")</generator>
EOF

# format RSS items
paste <(topics)	<(titles) <(downloads) <(sizes)	\
| awk -v FS=$'\t' -v URL="$URL_BASE" '
	NF == 4 {
		link = URL "/viewtopic.php?t=" $1

		print "<item><guid>" link "</guid>"
		print "<title>" $2 "</title>"
		print "<link>" link "</link>"
		print "<description>Size " $4 " / " $3 " downloads" "</description></item>"
	}

	END { print "</channel></rss>" }'

# vim: set ts=4 sw=4 tw=0 noet :
